service: movie-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: "*"

functions:
  getMovies:
    handler: functions/get_movies.handler
    events:
      - http:
          path: getmovies
          method: get
          cors: true

  getMoviesByYear:
    handler: functions/get_movies_by_year.handler
    events:
      - http:
          path: getmoviesbyyear/{year}
          method: get
          cors: true

  getMovieSummary:
    handler: functions/get_movie_summary.handler
    events:
      - http:
          path: getmoviesummary/{title}
          method: get
          cors: true

resources:
  Resources:
    MovieTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: movies
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
          - AttributeName: releaseYear
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
          - AttributeName: releaseYear
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
